version: "3"
networks:
  proxynet:
    driver: bridge

services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    networks:
        - proxynet
    ports:
      - "5000:5000"
